version: '3.2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: insta:latest
    volumes:
      - type: bind
        source: ../src
        target: /workdir
      - type: bind
        source: ../log
        target: /log
      - type: bind
        source: /Users/ikuta/Downloads/Picture
        target: /photos
      - type: bind
        source: /Users/ikuta/Downloads/Videos
        target: /videos
      - type: bind
        source: ../configs
        target: /configs
    working_dir: /workdir
    command: python main.py
